### ISSUE TITLE
Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [rsnodgrass/hass-lunos#1]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by rsnodgrass** [comment]
That would be great.     Though I hate CI that gets intrusive to the point it blocks developers from making judgement calls about whether to complete some step.
  

  
HACS is a good example right now that puts up a roadblock of requiring checking in logos/icons to another repository before allowing a PR.    An impediment that just adds friction to people who are contributing their time, where the value of that step is very low compared to the value of possibly losing someone adding an add-on to HACS default.    But that’s just my opinion ;).    
  

  
Packaged is fine. If it becomes an issue we can always change this later.
  

  
Thank you for proposing and implementing this!!!!
  
  

  
  
>

**Comment by KTibow** [comment]
Auto-formatting uses black and isort, so you can use their disable comments if you need to.
