### ISSUE TITLE
fan.set_speed service is deprecated, use fan.set_percentage or fan.set_preset_mode instead

### ISSUE THREAD

**Issue by Henry-Sir** [rsnodgrass/hass-lunos#5]
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:246
Integration: Ventilator ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 10. Februar 2022, 20:26:53 (1 occurrences)
Last logged: 10. Februar 2022, 20:26:53

The fan.set_speed service is deprecated, use fan.set_percentage or fan.set_preset_mode instead

**Comment by rsnodgrass** [comment]
Would you mind contributing a code change for this?  Since we cannot directly set the percentage on a LUNOS controller, it seems like the right behavior is having several modes (Low, Medium, High).  I wonder if the Summer Ventilation should also just be another preset instead of a separate service.

**Comment by rsnodgrass** [comment]
0.2.0 released
