### ISSUE TITLE
[Feature] Touch Air Comfort (TAC)

### ISSUE THREAD

**Issue by cs224** [rsnodgrass/hass-lunos#9]
I would be interested in understanding how I could operate the LUNOS e2 devices via Home Assistant AND the Touch Air Comfort (TAC) panel in parallel. Are there already some descriptions around on the internet? I'd appreciate a lot if you could give me some pointers in the right direction. Thanks!

**Comment by rsnodgrass** [comment]
Try asking on the [Home Assistant LUNOS discussion thread](https://community.home-assistant.io/t/lunos-heat-recovery-ventilation-hrv-fan-control/157287).
